// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGydEr8dNiHH5QpwiBZM_3kqODk5g_1z8',
    appId: '1:10558508194:web:a45d61c01f2082102c5bfb',
    messagingSenderId: '10558508194',
    projectId: 'errand-boys-acfeb',
    authDomain: 'errand-boys-acfeb.firebaseapp.com',
    storageBucket: 'errand-boys-acfeb.firebasestorage.app',
    measurementId: 'G-NY96B0ZB08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvrECZpxlYV5kUq4UZ-Ndn1vX0Ruofibk',
    appId: '1:10558508194:android:95661a82b326eff32c5bfb',
    messagingSenderId: '10558508194',
    projectId: 'errand-boys-acfeb',
    storageBucket: 'errand-boys-acfeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARl8tDfy3dBj15SfuOlHkD2TRz9dqaclk',
    appId: '1:10558508194:ios:ff380aa07b73bf0d2c5bfb',
    messagingSenderId: '10558508194',
    projectId: 'errand-boys-acfeb',
    storageBucket: 'errand-boys-acfeb.firebasestorage.app',
    iosBundleId: 'com.example.errandsBoys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARl8tDfy3dBj15SfuOlHkD2TRz9dqaclk',
    appId: '1:10558508194:ios:ff380aa07b73bf0d2c5bfb',
    messagingSenderId: '10558508194',
    projectId: 'errand-boys-acfeb',
    storageBucket: 'errand-boys-acfeb.firebasestorage.app',
    iosBundleId: 'com.example.errandsBoys',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGydEr8dNiHH5QpwiBZM_3kqODk5g_1z8',
    appId: '1:10558508194:web:70575e23eb33a6eb2c5bfb',
    messagingSenderId: '10558508194',
    projectId: 'errand-boys-acfeb',
    authDomain: 'errand-boys-acfeb.firebaseapp.com',
    storageBucket: 'errand-boys-acfeb.firebasestorage.app',
    measurementId: 'G-5YKYP7JN1W',
  );

}